# Generated by Django 2.2 on 2019-09-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_upload.Television'),
        ),
    ]
