# Generated by Django 2.1.5 on 2019-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0002_auto_20190207_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='test_field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
