# Generated by Django 2.2 on 2019-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0002_auto_20190913_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='television',
            name='tv_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
