# Generated by Django 2.1.5 on 2019-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0004_auto_20190213_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
