# Generated by Django 2.2 on 2019-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0005_auto_20190918_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='tv_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
