# Generated by Django 2.2 on 2019-09-13 20:00

from django.db import migrations, models
import django.db.models.deletion
import video_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Television',
            fields=[
                ('tv_id', models.AutoField(primary_key=True, serialize=False)),
                ('tv_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('tv_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=video_upload.models.Document.file_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('tv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video_upload.Television')),
            ],
        ),
    ]
