# Generated by Django 2.2 on 2019-07-29 19:31

from django.db import migrations, models
import video_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=video_upload.models.Document.file_path),
        ),
    ]
