# Generated by Django 2.2 on 2019-09-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0003_auto_20190918_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='tv_name',
            field=models.CharField(max_length=50),
        ),
    ]
