# Generated by Django 2.2 on 2019-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0004_auto_20190918_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
