# Generated by Django 2.2 on 2019-09-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0007_deletetv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeleteTv',
            new_name='Config',
        ),
    ]
