# Generated by Django 2.2 on 2019-09-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0008_auto_20190924_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
