# Generated by Django 2.2 on 2019-10-08 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0009_remove_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
