# Generated by Django 2.2 on 2019-10-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0010_auto_20191008_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_date',
        ),
    ]
