# Generated by Django 2.2 on 2019-10-10 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0014_auto_20191010_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
