# Generated by Django 2.2 on 2019-10-10 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0015_auto_20191010_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
